name: purify-template

on:
  pull_request:
    types:
      - closed
  workflow_dispatch:
    inputs:
      DIRECTORY_TO_REMOVE:
        description: "Directory to Remove"
        default: "solution"
      DIRECTORY_TO_CLEANSE:
        description: "Directory to Cleanse"
        default: "results"
      FILE_TO_REMOVE:
        description: "File to Remove"
        default: "dataFiles.zip"

jobs:
  remove_directories_and_files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.TEST_FILES_AUTH  }}
          ref: "template"

      - name: Find and remove instances of ${{ github.event.inputs.DIRECTORY_TO_REMOVE }}
        run: |
          find . -type d -name "${{ github.event.inputs.DIRECTORY_TO_REMOVE }}" -exec rm -rf "{}" \;
        continue-on-error: true

      - name: Find and remove files inside ${{ github.event.inputs.DIRECTORY_TO_CLEANSE }} instances
        run: |
          find . -type d -name "${{ github.event.inputs.DIRECTORY_TO_CLEANSE }}" -exec rm -rf "{}" \;
        continue-on-error: true

      - name: Find and remove instances of ${{ github.event.inputs.FILE_TO_REMOVE }}
        run: |
          find . -type f -name "${{ github.event.inputs.FILE_TO_REMOVE }}" -exec rm -f {} \;
        continue-on-error: true

      - name: Commit and push removal changes to the template branch
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}"
          git pull
          git add .
          git commit -m "Remove ${{ github.event.inputs.DIRECTORY_TO_REMOVE }}, files in ${{ github.event.inputs.DIRECTORY_TO_CLEANSE}}, and ${{ github.event.inputs.FILE_TO_REMOVE }}" --allow-empty
          git push origin HEAD:template
        if: |
          (success() && ${{ github.event.pull_request.merged }} == true && ${{ github.event.pull_request.base.ref }} == 'template') || ${{ github.event.workflow_run.event }} == 'workflow_run'
